### ISSUE TITLE
[Operator] Rollout Implementation

### ISSUE THREAD

**Issue by janlauber** [janlauber/one-click#8]
# CRUD

- [x] Deployments
- [x] Secrets
- [x] Env
- [x] HorizontalPodAutoscaler
- [x] Services
- [x] Ingresses
- [x] ServiceAccounts

## Enhancements

- [x] The operator should watch it's created resources and restore them when deleted.

Example Resource:

```yaml
apiVersion: one-click.io/v1alpha1
kind: Rollout
metadata:
  name: nginx
  namespace: test
spec:
  image:
    registry: docker.io
    repository: nginx
    tag: latest
  horizontalScale:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  env:
  - name: REFLEX_USERNAME
    value: admin
  - name: DEBUG
    value: "true"
  secrets: []
  volumes: []
  interfaces:
  - name: http
    port: 80
    ingress:
      ingressClass: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      rules:
      - host: reflex.oneclickapps.dev
        path: /test
        tls: false
      - host: reflex.oneclickapps.dev
        path: /test
        tls: false
  - name: https
    port: 8443
    ingress:
      ingressClass: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      rules:
      - host: reflex.oneclickapps.dev
        path: /
        tls: true
  serviceAccountName: nginx
```
